name: llm_env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - pandas
  - numpy
  - pip

  - pip:
    - openai
    - google-cloud-aiplatform
    - google-cloud-gemini
    - google-generative-ai
    - torch
    - transformers
    - 
    

