name: llm_env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - pandas
  - numpy
  - ipykernel
  - scikit-learn
  - pip

  - pip:
    - transformers
    - kaggle
    - matplotlib
    - nltk
    - contractions
    - textblob
    - datasets
    - peft
    - os
    - logging 
    - torch
    - pathlib 
    - pandas
    - sklearn.metrics
    - optuna
