name: llm_env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - pandas
  - numpy
  - ipykernel
  - scikit-learn
  - pip

  - pip:
    - openai
    - google-cloud-aiplatform
    - google-cloud-gemini
    - google.generativeai
    - torch
    - transformers
    - kaggle
    - matplotlib
    - genai
    - nltk
    - contractions
    - textblob
    - transformers
